CREATE TABLE labels (
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
name CHARACTER VARYING(255)
);

CREATE TABLE posts (
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
content CHARACTER VARYING(255),
created TIMESTAMP DEFAULT NOW(),
updated TIMESTAMP ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
post_status CHARACTER VARYING(30)
);

CREATE TABLE post_labels(
post_id INTEGER,
label_id INTEGER,
PRIMARY KEY(post_id, label_id),
CONSTRAINT fk_post_id FOREIGN KEY(post_id) REFERENCES posts(id),
CONSTRAINT fk_label_id FOREIGN KEY(label_id) REFERENCES labels(id)
 );

CREATE TABLE writers(
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
first_name CHARACTER VARYING(255),
last_name CHARACTER VARYING(255)
);

CREATE TABLE writer_posts(
writer_id INTEGER,
posts_id INTEGER,
UNIQUE(writer_id, posts_id),
FOREIGN KEY(writer_id) REFERENCES writers(id),
FOREIGN KEY(posts_id) REFERENCES posts(id)
);

